#!/bin/sh

#FIXME: not about what this file's all about (and in the README?)

install_to="$HOME/.bin"

if [ ! -e "$install_to" ]; then
  mkdir "$install_to"
fi

_install_bin_script() {
  if [ -z "$2" ]; then
    scriptname="$install_to/${1##*/}"
  else
    scriptname="$install_to/$2"
  fi

  curl --location --silent "$1" --output "$scriptname"
  chmod +x "$scriptname"
}

# cljs-watch (compiles clojurescript files)
_install_bin_script https://raw.githubusercontent.com/ibdknox/cljs-watch/master/cljs-watch

# ghi (shows github issues for a project)
_install_bin_script https://raw.githubusercontent.com/stephencelis/ghi/master/ghi

# gibo (outputs .gitignore templates)
_install_bin_script https://raw.githubusercontent.com/simonwhitaker/gibo/master/gibo

# lein (used for clojure project management)
_install_bin_script https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein

# rfc (displays RFCs)
_install_bin_script https://gist.githubusercontent.com/losingkeys/3902455/raw/rfc

# spark (makes graphs in the shell)
_install_bin_script https://raw.githubusercontent.com/holman/spark/master/spark

# dmenu-custom (script to open websites/programs in a terminal from dmenu)
_install_bin_script https://raw.githubusercontent.com/losingkeys/dmenu-custom/master/dmenu-custom

# boot (clojure build tool)
_install_bin_script https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh boot
