#!/bin/sh

if [ "$(id --user)" != "0" ]; then
  echo Please run this script as root
  exit 5
fi

if [ -z "$(command -v pacman)" ]; then
  echo \'pacman\' not found. Are you running Arch Linux?
  exit 127
fi

installScriptDirectory="$(dirname "$0")"
test -d install && installScriptDirectory=install
packagesToInstall="$(cat $installScriptDirectory/package-list)"

# pass --no-gui or -n to omit packages requiring graphical interfaces
if [ "$1" != '--no-gui' -a "$1" != '-n' ]; then
  installGUIPackages=true
  packagesToInstall="$packagesToInstall $(cat $installScriptDirectory/graphical-package-list)"
fi

pacman --sync --noconfirm --needed --color=auto "$packagesToInstall"

# install graphical vim (with clipboard support)
# if we're already installing GUI packages
if [ $installGUIPackages ]; then
  pacman --sync --noconfirm --needed --color=auto gvim
else
  pacman --sync --noconfirm --needed --color=auto vim
fi

# install packages from the Arch User Repository
# AUR home: https://aur.archlinux.org/
# and more info: https://wiki.archlinux.org/index.php/AUR
_install_from_aur() {
  # the first two characters of the package name
  # the AUR urls are of the format packages/pa/package-name/package-name.tar.gz
  # thanks: http://stackoverflow.com/a/219427
  firstTwo=$(echo "$1" | cut -c1-2)
  wget --quiet "https://aur.archlinux.org/packages/$firstTwo/$1/$1.tar.gz"
  tar xvf "$1.tar.gz"
  cd "$1"

  makepkg --asroot --syncdeps --noconfirm --install --needed

  cd ..
  rm "$1.tar.gz"
  rm --recursive "$1"
}

# _install_from_aur xf86-input-mtrack-git # needed for some macs
_install_from_aur asciinema
if [ $installGUIPackages ]; then
  _install_from_aur lighttable
  _install_from_aur minecraft
  _install_from_aur sublime-text
  _install_from_aur urxvt-font-size-git
fi
_install_from_aur automake-1.11 # needed for urlview
_install_from_aur chruby
_install_from_aur ctags-svn
_install_from_aur pipes-git
_install_from_aur urlview
_install_from_aur zsh-syntax-highlighting

# install packages from node.js' package manager
# more info on npm: https://www.npmjs.org/ and node.js: http://nodejs.org/
_install_from_npm() {
  npm install --global "$@"
}

_install_from_npm bower
_install_from_npm coffee-script
_install_from_npm ember-cli
_install_from_npm generator-jshint
_install_from_npm jsctags
_install_from_npm jsdoc
_install_from_npm jshint
_install_from_npm yo

_install_from_pip2() {
  pip2 install "$@"
}

_install_from_pip2 pygments

_install_from_cabal() {
  cabal update
  cabal install "$@"
}

_install_from_cabal alex happy # pandoc needs these to build
_install_from_cabal pandoc
_install_from_cabal hasktags stylish-haskell ghc-mod hlint
