#!/bin/sh

# shellcheck disable=2048
for package in $*; do
  curl -LO "https://aur.archlinux.org/cgit/aur.git/snapshot/$package.tar.gz"
  tar xvf "$package.tar.gz"

  cd "$package"
  makepkg --syncdeps --rmdeps --needed --install --noconfirm

  cd ..
  rm -rf "$package" "$package.tar.gz"
done
